---
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.30.0"
    hooks:
      - id: yamllint
