---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: init-build
  annotations:
    policies.kyverno.io/title: "Pod Init Build"
    policies.kyverno.io/subject: Pod
spec:
  background: false
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: init-build-init
      match:
        any:
          # AND across kinds and selector
          - resources:
              # OR inside list of kinds
              kinds:
                - Pod
              annotations:
                init-build.kroche.co/enabled: "true"
      preconditions:
        all:
        - key: "{{request.operation || 'BACKGROUND'}}"
          operator: NotEquals
          value: DELETE
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - name: init-build
                image: gcr.io/kaniko-project/executor:debug
                command: ["/bin/sh", "-x", "-c"]
                args:
                  - >-
                    /kaniko/executor
                    --context='{{request.object.metadata.annotations."init-build.kroche.co/context"}}'
                    --context-sub-path='''{{
                      not_null(
                        request.object.metadata.annotations."init-build.kroche.co/context-sub-path",
                        './.'
                      )
                    }}'''
                    --dockerfile='''{{
                      not_null(
                        request.object.metadata.annotations."init-build.kroche.co/dockerfile",
                        'Dockerfile'
                      )
                    }}'''
                    --destination='registry.dev.kroche.co/{{request.object.metadata.namespace}}/{{request.object.metadata.annotations."init-build.kroche.co/image"}}'
                    --cache=true
                    --cache-copy-layers=true
                    --cache-repo='registry.dev.kroche.co/{{request.object.metadata.namespace}}/cache'
                    {{ request.object.metadata.annotations."init-build.kroche.co/extra-args" || '' }}
    - name: init-build-change
      match:
        any:
          # AND across kinds and selector
          - resources:
              # OR inside list of kinds
              kinds:
                - Pod
              annotations:
                init-build.kroche.co/enabled: "true"
      preconditions:
        all:
        - key: "{{request.operation || 'BACKGROUND'}}"
          operator: NotEquals
          value: DELETE
      mutate:
        foreach:
          - list: "request.object.spec.containers"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: >-
                      {{ regex_replace_all_literal(
                        '^{{ request.object.metadata.annotations."init-build.kroche.co/image" }}$',
                        '{{ element.image }}',
                        'registry.dev.kroche.co/{{ request.object.metadata.namespace }}/{{ request.object.metadata.annotations."init-build.kroche.co/image" }}'
                      ) }}
                    imagePullPolicy: Always
