---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-dev-kroche-co
spec:
  secretName: registry-dev-kroche-co
  dnsNames:
    - registry.dev.kroche.co
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    group: cert-manager.io
