---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: docker-registry
  name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: REGISTRY_HTTP_ADDR
              value: ":443"
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/tls.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/tls.key
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: image-store
              mountPath: "/var/lib/registry"
            - name: certs
              mountPath: "/certs"
              readOnly: true
      volumes:
        - name: image-store
          emptyDir: {}
        - name: certs
          secret:
            secretName: registry-dev-kroche-co
