---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth
    server: "https://kubernetes.default.svc"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
    retry:
      limit: 15
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
  source:
    repoURL: "https://charts.dexidp.io"
    targetRevision: "~0.14.1"
    chart: "dex"
    helm:
      releaseName: dex
      values: |
        envVars:
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dex-oauth-creds
                key: client-id
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-oauth-creds
                key: client-secret
          - name: GITHUB_ARGOCD_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dex-oauth-creds
                key: argocd-client-id
          - name: GITHUB_ARGOCD_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-oauth-creds
                key: argocd-client-secret
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-issuer"
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          hosts:
            - host: dex.kroche.co
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: dex.kroche.co
              hosts:
                - dex.kroche.co
        config:
          issuer: https://dex.kroche.co
          storage:
            type: kubernetes
            config:
              inCluster: true
          enablePasswordDB: true
          # oauth2:
          #   skipApprovalScreen: true
          #   alwaysShowLoginScreen: false
          connectors:
            - type: github
              id: github
              name: GitHub
              config:
                clientID: $GITHUB_CLIENT_ID
                clientSecret: $GITHUB_CLIENT_SECRET
                redirectURI: https://dex.kroche.co/callback
                orgs:
                  - name: kroche-co
              loadAllGroups: false
              teamNameField: slug
              useLoginAsID: true
          logger:
            level: "debug"
          staticClients:
            - id: oauth2-proxy
              redirectURIs:
                - "https://oauth2-proxy.kroche.co/oauth2/callback"
              name: "OAuth2 Proxy"
              secret: "b2F1dGgyLXByb3h5LWNsaWVudC1zZWNyZXQK"
        serviceMonitor:
          enabled: true
