---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aoai-bot
spec:
  description: "Project for AOAI Bot"
  destinations:
    - namespace: "aoai-bot"
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
  sourceNamespaces:
    - "aoai-bot"
