---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: requests-counter
  name: requests-counter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: requests-counter
  template:
    metadata:
      annotations:
        init-build.kroche.co/enabled: "true"
        init-build.kroche.co/context: >
          git://github.com/kroche-co/requests-counter.git
        init-build.kroche.co/image: "requests-counter"
      labels:
        app.kubernetes.io/name: requests-counter
    spec:
      containers:
        - name: main
          image: requests-counter
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          resources: {}
