---
apiVersion: v1
kind: Service
metadata:
  name: requests-counter
spec:
  selector:
    app.kubernetes.io/name: requests-counter
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
  externalTrafficPolicy: Local
