---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: "45.x.x"
    chart: "kube-prometheus-stack"
    helm:
      releaseName: kube-prometheus-stack
      values: |-
        prometheus:
          prometheusSpec:
            scrapeInterval: 30s
            evaluationInterval: 30s
        grafana:
          serviceMonitor:
            enabled: true
          grafana.ini:
            server:
              enable_gzip: true
              domain: grafana.kroche.co
              root_url: https://grafana.kroche.co:443
            auth:
              oauth_auto_login: true
            auth.github:
              enabled: true
              allow_sign_up: true
              auto_login: true
              client_id: "${GH_CLIENT_ID}"
              client_secret: "${GH_CLIENT_SECRET}"
              scopes: "user:email,read:org"
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              allowed_organizations: "kroche-co"
            users:
              auto_assign_org_role: Editor
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-issuer"
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            hosts:
              - grafana.kroche.co
            path: /
            tls:
              - secretName: grafana-kroche-co
                hosts:
                  - grafana.kroche.co
